### PR TITLE
Authenticity, enhancements, etc

### PR DESCRIPTION
**Pull request by man-of-eel**
- Real gun sprite
- Real gun sound
- Enemy death sounds
- Gun follows mouse
- Cursor offset fixed
- Few other things

Some of the commits are made by BuildTools or invalid-email-address, not too familiar with Git so I hope it isn't an issue

### CODE REVIEW

**Comment by vivirenremoto** [comment]
hello!

wow! i really like your changes.

I only have one objection to merge it, the cheat code "idkfa" to use the shotgun made by Jaap Brasser is broken, if you can fix it i will appreciate it :)

i'm not sure if you know how to use write the cheat code (i just forgoted it), just click the button on/off sound, then if you press any key a textarea will appear from top.

**Comment by man-of-eel** [comment]
I could never get the cheats to work on your version either, so not sure. Firefox issue maybe?

**Comment by vivirenremoto** [comment]
i just tried on firefox/chrome desktop (windows) and the cheat code input works, just click in the button on or off one time, then immediately press a key to see the input, try again

**Comment by vivirenremoto** [comment]
or try this, open the captcha.html in your browser for example
https://vivirenremoto.github.io/doomcaptcha/captcha.html

then in the browser console paste this code to show the cheat code input
$('#cheatcode').css('opacity',1);

**Comment by man-of-eel** [comment]
Figured it out..
```js
if (screen.width > 1500) {
        $('#cheatcode').show().val('').focus();
    }
```
My screen is 1366x768, so it didn't trigger. I will fix that and the shotgun for the gun flash real quick

**Comment by vivirenremoto** [comment]
Ok! I will merge soon as posible

**Comment by man-of-eel** [comment]
Should be good now

**Comment by vivirenremoto** [comment]
thank you! i would like to give you some credit for your work, do you want to appear in "You rock!" section ? you want to put you real name or just man-of-eel ?

**Pull request merged**
